"""
Fix Collinearity in Texel Tuned Weights
=======================================
Centers the PSTs (mean 0) and pushes the offset into the base Material values.
Then normalizes everything so MG Pawn = 100.
"""

import os
import sys

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _PROJECT_ROOT)

import algorithms.tuned_weights as tw
import chess
import numpy as np

def fix_weights():
    # Collect all parameters
    mg_mat = dict(tw.MG_VALUE)
    eg_mat = dict(tw.EG_VALUE)
    
    psts = {
        "MG_PAWN_TABLE": list(tw.MG_PAWN_TABLE), "EG_PAWN_TABLE": list(tw.EG_PAWN_TABLE),
        "MG_KNIGHT_TABLE": list(tw.MG_KNIGHT_TABLE), "EG_KNIGHT_TABLE": list(tw.EG_KNIGHT_TABLE),
        "MG_BISHOP_TABLE": list(tw.MG_BISHOP_TABLE), "EG_BISHOP_TABLE": list(tw.EG_BISHOP_TABLE),
        "MG_ROOK_TABLE": list(tw.MG_ROOK_TABLE), "EG_ROOK_TABLE": list(tw.EG_ROOK_TABLE),
        "MG_QUEEN_TABLE": list(tw.MG_QUEEN_TABLE), "EG_QUEEN_TABLE": list(tw.EG_QUEEN_TABLE),
        "MG_KING_TABLE": list(tw.MG_KING_TABLE), "EG_KING_TABLE": list(tw.EG_KING_TABLE),
    }
    
    bonuses = {
        "DOUBLED_PAWN_PENALTY": tw.DOUBLED_PAWN_PENALTY,
        "ISOLATED_PAWN_PENALTY": tw.ISOLATED_PAWN_PENALTY,
        "BISHOP_PAIR_BONUS": tw.BISHOP_PAIR_BONUS,
        "ROOK_OPEN_FILE_BONUS": tw.ROOK_OPEN_FILE_BONUS,
        "ROOK_SEMI_OPEN_FILE_BONUS": tw.ROOK_SEMI_OPEN_FILE_BONUS,
        "KING_SHIELD_BONUS": tw.KING_SHIELD_BONUS,
    }

    # 1. Center PSTs
    pieces = [
        ("PAWN", chess.PAWN), ("KNIGHT", chess.KNIGHT), ("BISHOP", chess.BISHOP),
        ("ROOK", chess.ROOK), ("QUEEN", chess.QUEEN), ("KING", chess.KING)
    ]
    
    for name, pt in pieces:
        # MG
        mg_name = f"MG_{name}_TABLE"
        mg_mean = np.mean(psts[mg_name])
        psts[mg_name] = [v - mg_mean for v in psts[mg_name]]
        if pt != chess.KING:
            mg_mat[pt] += mg_mean
            
        # EG
        eg_name = f"EG_{name}_TABLE"
        eg_mean = np.mean(psts[eg_name])
        psts[eg_name] = [v - eg_mean for v in psts[eg_name]]
        if pt != chess.KING:
            eg_mat[pt] += eg_mean

    # 2. Rescale to MG Pawn = 100
    scale = 100.0 / mg_mat[chess.PAWN]
    print(f"Scale factor: {scale:.4f}")
    
    for pt in mg_mat:
        mg_mat[pt] *= scale
        eg_mat[pt] *= scale
        
    for name in psts:
        psts[name] = [v * scale for v in psts[name]]
        
    for name in bonuses:
        bonuses[name] *= scale

    # 3. Write back to tuned_weights.py
    output_path = os.path.join(_PROJECT_ROOT, "algorithms", "tuned_weights.py")
    lines = [
        '"""',
        'Tuned Evaluation Weights',
        '========================',
        'Auto-generated by texel_tuning.py (L-BFGS-B)',
        'PSTs centered, then normalized so MG_PAWN = 100.',
        '"""',
        '', 'import chess', '', '# ── Material Values ──',
        f'MG_VALUE = {{chess.PAWN: {int(round(mg_mat[chess.PAWN]))}, chess.KNIGHT: {int(round(mg_mat[chess.KNIGHT]))}, chess.BISHOP: {int(round(mg_mat[chess.BISHOP]))}, chess.ROOK: {int(round(mg_mat[chess.ROOK]))}, chess.QUEEN: {int(round(mg_mat[chess.QUEEN]))}, chess.KING: 0}}',
        f'EG_VALUE = {{chess.PAWN: {int(round(eg_mat[chess.PAWN]))}, chess.KNIGHT: {int(round(eg_mat[chess.KNIGHT]))}, chess.BISHOP: {int(round(eg_mat[chess.BISHOP]))}, chess.ROOK: {int(round(eg_mat[chess.ROOK]))}, chess.QUEEN: {int(round(eg_mat[chess.QUEEN]))}, chess.KING: 0}}',
        ''
    ]
    
    table_names = [
        "MG_PAWN_TABLE", "EG_PAWN_TABLE", "MG_KNIGHT_TABLE", "EG_KNIGHT_TABLE",
        "MG_BISHOP_TABLE", "EG_BISHOP_TABLE", "MG_ROOK_TABLE", "EG_ROOK_TABLE",
        "MG_QUEEN_TABLE", "EG_QUEEN_TABLE", "MG_KING_TABLE", "EG_KING_TABLE",
    ]
    for name in table_names:
        lines.append(f"{name} = [")
        for rank in range(8):
            row = psts[name][rank*8 : rank*8+8]
            lines.append("    " + ", ".join(f"{int(round(x)):>4}" for x in row) + ",")
        lines.append("]\n")

    lines.append("# ── Bonuses ──")
    for name in bonuses:
        lines.append(f"{name} = {int(round(bonuses[name]))}")
    lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Fixed weights saved to {output_path}")
    print(f"MG Pawn: {mg_mat[chess.PAWN]:.1f}, MG Knight: {mg_mat[chess.KNIGHT]:.1f}, MG Queen: {mg_mat[chess.QUEEN]:.1f}")


if __name__ == "__main__":
    fix_weights()
